# SMTP Configuration
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.user=tehilaruzindana@gmail.com
mail.smtp.password=ttzi jelt jsho hlqe

# Database Configuration
db.url=jdbc:postgresql://localhost:5432/ems_db
db.user=postgres
db.password=
